---
name: Content Submission
description: Let us know what content you want to create
title: "[Content]: "
labels: ["content"]
projects: "SolaceLabs/5"
body:
  - type: checkboxes
    id: content_type
    attributes:
      label: "Which type(s) of content are you submitting?"
      description: "Select all that apply. These will be added as labels to your issue."
      options:
        - label: "code repository"
        - label: "video"
        - label: "blog"
        - label: "codelab"
        - label: "community post"
  - type: textarea
    id: description
    attributes:
      label: Content Description
      description: A description of the content you are submitting.
    validations:
      required: true
  - type: textarea
    id: extra_info
    attributes:
      label: Extra Information
      description: Anything else we should know?
    validations:
      required: false
