---
name: Content Submission
description: Let us know what content you want to create
title: "[Content]: "
labels:
  - content
  - code repository
  - video
  - blog
  - codelab
  - community post
projects:
  - "SolaceLabs/5"
body:
  - type: textarea
    id: description
    attributes:
      label: Content Description
      description: A description of the content you are submitting.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to contribute content! We have pre-filled labels for each content type. Please remove the labels that don't apply to the content you are creating.
        - Blog
        - Codelab
        - Code Repository
        - Community Post
        - Video

  - type: textarea
    id: extra_info
    attributes:
      label: Extra Information
      description: Anything else we should know?
    validations:
      required: false
